version: '3.7'

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      my-network:
        ipv4_address: 172.16.238.10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: 172.16.238.20
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
    depends_on:
      - db
    networks:
      my-network:
        ipv4_address: 172.16.238.30

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3306:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      my-network:
        ipv4_address: 172.16.238.20

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.238.0/24"
